- build.gradle
- config/owasp/suppressions.xml
> Update testcontainers for Docker related bug

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11025
Review and Resolve Remaining CVEs Where Possible
```
[ ] Yes
[X] No
```
> RDM-11025 initial commit

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/ccd/service/MessagePublisherRunnableIT.java
- src/integrationTest/resources/sql/insert-message-property-candidates.sql
- src/main/java/uk/gov/hmcts/ccd/config/CcdMessageConverter.java
- src/main/java/uk/gov/hmcts/ccd/config/JacksonConfiguration.java
- src/main/java/uk/gov/hmcts/ccd/service/MessageProperties.java
- src/test/java/uk/gov/hmcts/ccd/config/CcdMessageConverterTest.java
https://tools.hmcts.net/jira/browse/RDM-11155
Align JSON with data store
Ensure content-type is set correctly for ASB
```
[ ] Yes
[x] No
```
> RDM-11155 - Align JSON format with data store

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-11234
Upgrade Hikari CP Dependency in All CCD Apps
```
[ ] Yes
[X] No
```
> RDM-11234 Upgrade Hikari CP Dependency in All CCD Apps

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11529
CVE-2021-25122 (Message Publisher)
```
[ ] Yes
[X] No
```
> RDM-11529 CVE-2021-25122 (Message Publisher)

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11380
CVE-2017-1000190
```
[ ] Yes
[ ] No
```
> RDM-11380 CVE-2017-1000190

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11765
Update CVE Suppress Until Date In All Services
```
[ ] Yes
[X] No
```
> RDM-11765 Update CVE Suppress Until Date In All Services

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-11729
```
[ ] Yes
[ ] No
```
> RDM-11729: Upgrade befta to 6.13.0

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11825
```
[ ] Yes
[ ] No
```
> RDM-11825: Suppress CVE to be fixed in later ticket

- build.gradle
https://tools.hmcts.net/jira/browse/RDM-11809
CVE-2021-21295 (CCD Message Publisher)
```
[ ] Yes
[X] No
```
> RDM-11809 CVE-2021-21295 (CCD Message Publisher)

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11531
CVE-2020-13697
```
[ ] Yes
[ ] No
```
> RDM-11531 CVE-2020-13697

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-12118
CVE-2021-21409 (ccd-message-publisher)
```
[ ] Yes
[X] No
```
> RDM-12118 CVE-2021-21409 (ccd-message-publisher)

- charts/ccd-message-publisher/Chart.yaml
https://tools.hmcts.net/jira/browse/RDM-12054
Upgrade Base Chart Versions (Java & Nodejs)
```
[ ] Yes
[X] No
```
> RDM-12054 Upgrade Base Chart Versions (Java & Nodejs)

- charts/ccd-message-publisher/values.aat.template.yaml
- config/owasp/suppressions.xml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDM-11097
```
[ X] Yes
[ ] No
```
> RDM-11097: CCD-DATA-STORE: Upgrade to Postgres 11 on PROD

- charts/ccd-message-publisher/values.aat.template.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDM-11097
```
[X ] Yes
[ ] No
```
> RDM-11097: message publisher revert (postgres v11 db cleanup)

- charts/ccd-message-publisher/values.yaml
> fixed vault entry

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1562
updated json-smart library version
```
[ ] Yes
[ ] No
```
> updated json-smart library version

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1359
fix for CVE-2021-29425
```
[ ] Yes
[x] No
```
> fix for CVE-2021-29425

- charts/ccd-message-publisher/Chart.yaml
CCD-1711
```
[ ] Yes
[x] No
```
> Update Chart.yaml Java -> 3.6.0

- build.gradle
- config/owasp/suppressions.xml
Resolve CVE-2021-28170
```
[ ] Yes
[x] No
```
> CCD-1858 Resolve CVE-2021-28170

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2357
Amending suppression dates by 1 month
```
[ ] Yes
[X ] No
```
> Amend suppression dates by 1 month

- Jenkinsfile_CNP
- build.gradle
- src/aat/java/uk.gov.hmcts.ccd.messagepublisher/befta/MessagePublisherTestAutomationAdapter.java
- src/aat/java/uk.gov.hmcts.ccd.messagepublisher/befta/TestDataLoaderMain.java
- topic-reader-util/build.gradle
https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```
> Update to build.gradle

- charts/ccd-message-publisher/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
> helm update

- charts/ccd-message-publisher/Chart.yaml
> Upgrade to Latest Base Helm Charts

- build.gradle
N/A
Upgrade ccd-test-definitions version as the builds are failing with that old version.
```
[ ] Yes
[X] No
```
> upgrade test defs version

- config/owasp/suppressions.xml
> --Adding the Suppression for Spring Beans jar. Temporary Fix.

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-2930
```
[ ] Yes
[ ] No
```
> spring framework version update to 5.3.18 from 5.3.15

- config/owasp/suppressions.xml
There are several dependency check failures, this change is suppressing them.
```
[ ] Yes
[ x] No
```
> CVE Multiple issues suppressions

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3105
```
[ ] Yes
[x] No
```
> package update for CVE-2022-21724

- Dockerfile
https://tools.hmcts.net/jira/browse/CCD-3207
Added switch to non-root user in Dockerfile
```
[ ] Yes
[X] No
```
> CCD-3207 - Added switch to non-root user in Dockerfile

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3359
CCD-3334 Regular Pipeline Maintenance - suppression CVE-2022-22978
```
[ ] Yes
[ x] No
```
> CCD-3334 Regular Pipeline Maintenance - suppression CVE-2022-22978

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3400
Suppression for CVE-2022-22950
```
[ ] Yes
[X] No
```
> CCD-3400: Suppression for CVE-2022-22950

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3405
https://tools.hmcts.net/jira/browse/CCD-3407
https://tools.hmcts.net/jira/browse/CCD-3408
https://tools.hmcts.net/jira/browse/CCD-3409
Marked CVE-2018-11039, CVE-2018-11040, CVE-2018-1257 and CVE-2020-5421 as false positives
```
[ ] Yes
[x] No
```
> CCD-3405: Move to False positives section

- charts/ccd-message-publisher/Chart.yaml
- config/owasp/suppressions.xml
n/a
Add comment to suppressions.xml
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Add comment to suppressions.xml

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3448
CCD-3448 : Update suppressions.xml (CVE-2022-33915)
```
[ ] Yes
[X] No
```
> CCD-3448 : Update suppressions.xml (CVE-2022-33915)

- charts/ccd-message-publisher/Chart.yaml
- charts/ccd-message-publisher/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CCD-3434
Upgrade Java, postgresql and redis configurations
```
[ ] Yes
[x] No
```
> CCD-3434 Upgrade Java, postgresql and redis configurations

- charts/ccd-message-publisher/Chart.yaml
> Update Chart.yaml bumping chart to fix ordering issue

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-3504
Upgrade to latest java plugin in all the repositories
```
[ ] Yes
[ x] No
```
> CCD-3504 Upgrade to latest java plugin - java plugin upgraded to 0.12.27

- config/owasp/suppressions.xml
CCD-3605 (https://tools.hmcts.net/jira/browse/CCD-3605)
Updated suppressions file to temporarily suppress CVE-2022-31197.
```
[ ] Yes
[x] No
```
> CCD-3605: Temporarily suppress CVE-2022-31197

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions
```
[ ] Yes
[ x] No
```
> CCD-3577 Cleanup CVE Suppressions 

- build.gradle
- config/owasp/suppressions.xml
Removal of suppression and addition of ext['snakeyaml.version'] = '1.31' into build.gradle
```
[ ] Yes
[X] No
```
> CCD-3658-CVE-2022-25857-Fix

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4056
CVE-2016-4432 CVE-2016-3094 Suppression
```
[ ] Yes
[ x] No
```
> CCD-4056 CVE-2016-4432 CVE-2016-3094 Suppression

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4043
Replace fasterxml.jackson release candidate with prod-ready version
```
[ ] Yes
[ x] No
```
> CCD-4043 Fasterxml Jackson Upgrade

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4150
CVE-2022-41881
CVE-2022-41915
```
[ ] Yes
[ ] No
```
> CCD-4150 Update to Netty dependencies to fix CVEs

- .github/workflows/dependency-check.yml
- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4163
https://tools.hmcts.net/jira/browse/CCD-4150
https://tools.hmcts.net/jira/browse/CCD-4086
Bump rse-gradle-java-plugin
Remove Suppressions:
- CVE-2022-41881
- CVE-2022-41915
- CVE-2021-37533
```
[ ] Yes
[ x] No
```
> CCD-4163 Bump rse-gradle-java-plugin

- charts/ccd-message-publisher/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```
> CCD-4317 Upgrade base charts

- charts/ccd-message-publisher/Chart.yaml
- charts/ccd-message-publisher/values.preview.template.yaml
- config/owasp/suppressions.xml
CIV-7862 - Update ServiceBus Chart Version
```
[ ] Yes
[ x ] No
```
> CIV-7862 - Update ServiceBus Chart Version

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4479
https://tools.hmcts.net/jira/browse/CCD-4509
Fix for [CVE-2023-20861](https://github.com/advisories/GHSA-564r-hj7v-mcr5)
Fix for CVE-2023-20860
upgrade Spring Framework version to 5.3.26
```
[ ] Yes
[ ] No
```
> CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860 

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4056
re-add suppression
```
[ ] Yes
[X] No
```
> CCD-4056 : Update suppressions.xml

- Jenkinsfile_CNP
- build.gradle
- charts/ccd-message-publisher/Chart.yaml
- charts/ccd-message-publisher/values.yaml
https://tools.hmcts.net/jira/browse/CCD-4866
Updates to resolve issue with repo no longer logging to app insights
```
[ ] Yes
[X] No
```
> update for appinsights fix

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4970
Bumped guava, removed suppression
```
[ ] Yes
[X] No
```
> CCD-4970 : Fix CVE-2020-8908

- acb.tpl.yaml
- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5045
> CCD-5045 : Fix acb entries to fix timeout issue

- charts/ccd-message-publisher/values.aat.template.yaml
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5162
Updating values.aat.template.yaml with V15 secrets for staging 
```
[ ] Yes
[x] No
```
> Updating staging with V15 secrets

- config/owasp/suppressions.xml
CCD-5024 
Suppression removed
```
[ ] Yes
[X] No
```
> CCD-5024 - Update suppressions.xml

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5136
Changes made to resolve CVE
```
[ ] Yes
[x] No
```
> CVE fixes 010224

- build.gradle
- config/owasp/suppressions.xml
REVERT: https://github.com/hmcts/ccd-message-publisher/pull/276
https://tools.hmcts.net/jira/browse/CCD-4972
Fix https://github.com/advisories/GHSA-q3mw-pvr8-9ggc : Update org.apache.tomcat.embed to 9.0.82
```
[ ] Yes
[ ] No
```
> Revert pr276

- src/main/java/uk/gov/hmcts/ccd/service/MessageProperties.java
> Force new build

- build.gradle
- src/main/java/uk/gov/hmcts/ccd/MessagePublisherApplication.java
- src/main/resources/application.yaml
Reverts hmcts/ccd-message-publisher#288
> Revert "CCD-5316 - Use latest Service Bus library"

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5020
Netty version bump to resolve CVE 34462
```
[ ] Yes
[X] No
```
> 5020 Netty version bump to resolve CVE 34462

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5201
Updated Spring Security to resolve CVE
```
[ ] Yes
[X] No
```
> CCD-5201 PR to resolve CVE-2023-34042

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5476
CCD-5476: CVE-2023-34462 : removed suppression, no longer required
```
[ ] Yes
[X] No
```
> CCD-5476: CVE-2023-34462 : removed suppression, no longer required

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5475
https://tools.hmcts.net/jira/browse/CCD-5475
```
[ ] Yes
[X] No
```
> CCD-5475: bumped tomcat version to 9.0.82

- charts/ccd-message-publisher/Chart.yaml
Needed for ASO upgrade (which is needed to fix throttling issue in ASO)
```
[ ] Yes
[ ] No
```
> Chart upgrades (servicebus and java)

- build.gradle
- charts/ccd-message-publisher/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5022
Fix CVE-2023-36414/5 - upgrade libraries
```
[ ] Yes
[x] No
```
> CCD-5022 False Positive suppress CVE-2023-36414/5

- config/owasp/suppressions.xml
[CCD-4971](https://tools.hmcts.net/jira/browse/CCD-4971)
```
[ ] Yes
[x] No
```
> remove fixed CVEs from suppression file

- build.gradle
- charts/ccd-message-publisher/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5158
Fix CVE-2023-46589 (all CCD repos)
```
[ ] Yes
[x] No
```
> CCD-5158 Upgrade Tomcat to fix CVE

- .github/workflows/dependency-check.yml
- Dockerfile
- README.md
- acb.tpl.yaml
- build.gradle
- topic-reader-util/build.gradle
https://tools.hmcts.net/jira/browse/CME-54
Update to Java 21
```
[ ] Yes
[x] No
```
> CME-54 update to Java 21

- config/owasp/suppressions.xml
CCD-5952
Removed suppression
```
[ ] Yes
[X] No
```
> CCD-5952: Fix-CVE-2024-43591

- config/owasp/suppressions.xml
> remove redundant CVE enteries

- charts/ccd-message-publisher/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```
> CCD-6193 update base chart versions

- build.gradle
https://tools.hmcts.net/jira/browse/CME-674
Replaced JitPack with Azure Artifacts and updated Fortify client
```
[ ] Yes
[X] No
```
> CME-674 Replaced JitPack with Azure Artifacts
